---
Afghanistan: AF
Albania: AL
Algeria: DZ
Andorra: AD
Angola: AO
Antigua-and-Barbuda: AG
Argentina: AR
Armenia: AM
Aruba: AW
Australia: AU
Austria: AT
Azerbaijan: AZ
Bahamas: BS
Bahrain: BH
Bangladesh: BD
Barbados: BB
Belarus: BY
Belgium: BE
Belize: BZ
Benin: BJ
Bermuda: BM
Bhutan: BT
Bolivia: BO
Bosnia-and-Herzegovina: BA
Botswana: BW
Brazil: BR
Brunei: BN
Bulgaria: BG
Burkina-Faso: BF
Burundi: BI
Cambodia: KH
Cameroon: CM
Canada: C
Cape-Verde: CV


